// ForbiddenWords.js
const forbiddenWords = [
    'sexual',
    'nude',
    'porn',
    'xxx',
    'sex',
    'erotic',
    'adult',
    'dildo',
    'vibrator',
    'hentai',
    'fetish',
    'sex toy',
    'prostitute',
    'hooker',
    'strippers',
    'pornography',
    'swingers',
    'naked',
    'orgy',
    'bdsm',
    'kinky',
    'lesbian',
    'gay',
    'bisexual',
    'transgender',
    'queer',
    'sexuality',
    'intercourse',
    'foreplay',
    'masturbate',
    'cum',
    'climax',
    'orgasm',
    'fleshlight',
    'suck',
    'blowjob',
    'handjob',
    'bukkake',
    'fingering',
    'striptease',
    'latina',
    'milf',
    'cougar',
    'slut',
    'whore',
    'prostitution',
    'escort',
    'naughty',
    'sexy',
    'temptation',
    'horny',
    'seduction',
    'aphrodisiac',
    'swinging',
    'voyeur',
    'erotica',
    'fetishes',
    'peep',
    'hardcore',
    'softcore',
    'sex worker',
    'pillow talk',
    'booty',
    'ass',
    'tits',
    'boobs',
    'pussy',
    'dick',
    'cock',
    'penis',
    'vagina',
    'anus',
    'clitoris',
    'breasts',
    'orgasmic',
    'horniness',
    'sexual acts',
    'xxx rated',
    'sexually explicit',
    'lactating',
    'furry',
    'swinger',
    'threesome',
    'fourplay',
    'adult content',
    'sexting',
    'sexual harassment',
    'erotic literature',
    'fetishism',
    'sexual fantasy',
    'sexual preference',
    'kink',
    'gagging',
    'anal',
    'blow job',
    'fuck',
    'fucking',
    'cocksucker',
    'bitch',
    'femme',
    'guy',
    'girl',
    'dirty talk',
    'sensual',
    'sex education',
    'sexy time',
    'lap dance',
    'dirty',
    'stimulation',
    'sensation',
    'foreplay',
    'sex appeal',
    'turn on',
    'seduce',
    'tease',
    'panties',
    'thong',
    'g-string',
    'nipple',
    'crotch',
    'sexual',
    'nudista',
    'pornografía',
    'xxx',
    'sexo',
    'erótico',
    'adulto',
    'dildo',
    'vibrador',
    'fetiche',
    'desnudo',
    'orgía',
    'bdsm',
    'sodomía',
    'lesbiana',
    'gay',
    'bisexual',
    'transgénero',
    'queer',
    'intercurso',
    'fornicar',
    'masturbarse',
    'eyacular',
    'clímax',
    'orgasmo',
    'semen',
    'goloso',
    'chupar',
    'felación',
    'manipulación',
    'cachondo',
    'prostituta',
    'putana',
    'puto',
    'zorra',
    'polla',
    'vagina',
    'pene',
    'culo',
    'teta',
    'tetas',
    'nalgas',
    'follador',
    'follando',
    'sexy',
    'lascivo',
    'incitación',
    'seducción',
    'temor',
    'apetito',
    'inhibición',
    'caricia',
    'dulzura',
    'sensualidad',
    'explícito',
    'erotismo',
    'paseo',
    'calentura',
    'desinhibido',
    'tacaño',
    'escorte',
    'sex shop',
    'sexting',
    'camarera',
    'follón',
    'aguijón',
    'kinky',
    'deseo',
    'seductor',
    'coito',
    'picha',
    'chico',
    'chica',
    'charlas sucias',
    'incitación',
    'desahogo',
    'depravación',
    'sádico',
    'sadomasoquista',
    'película XXX',
    'caliente',
    'lujuria',
    'autoerotismo',
    'relaciones sexuales',
    'coqueteo',
    'tentación',
    'nalguear',
    'carnal',
    'pervertido',
    'juguete sexual',
    'desahogar',
    'embriagar',
    'adultos',
    'afrodisíaco',
    'interacción',
    'cita',
    'placer',
    'planteamiento',
    'proposición',
    'intimidad',
    'tentador',
    'flirteo',
    'suspenso',
    'atractivo',
    'desinhibido',
    'sodomita',
    'orgásmico',
    'carnalidad',
    'perversión',
    'incesto',
    'desviación',
    'desahogo',
    'excitación',
    'impúdico',
    'lujurioso',
    'cuerpos',
    'erógeno',
    'pecado',
    'desviación',
    'inmoral',
    'prostitución',
    'escandaloso',
    'follador',
    'transgresión',
    'caricias',
    'deseos',
    'frivolidad',
    'suspenso',
    'picante',
    'proposición',
    'infidelidad',
    'seducción',
    'conquista',
    'triángulo amoroso',
    'crush',
    'coito',
    'voyerista',
    'salsosa',
    'perversa',
    'pelo',
    'frontal',
    'fantasía',
    'pecaminoso',
    'licencioso',
    'depravado',
    'fascinación',
    'atracción',
    'cortejo',
    'encuentro',
    'química',
    'promiscuo',
    'frivolo',
    'exhibicionismo',
    'calor',
    'encanto',
    'instinto',
    'mentira',
    'desenfreno',
    'tabú',
    'tente',
    'provocador',
    'hormonas',
    'seductor',
    'tergiversar',
    'escabroso',
    'chico malo',
    'coqueteo',
    'enamoramiento',
    'relación tóxica',
    'infatuación',
    'conexión',
    'deseo',
    'trasgresor',
    'sorpresa',
    'excentricidad',
    'sorpresa',
    'agresivo',
    'compulsivo',
    'perversidad',
    'adicción',
    'caloroso',
    'invitación',
    'manipulador',
    'desinhibición',
    'morboso',
    'aventura',
    'lujuriosa',
    'apetito',
    'coqueteos',
    'relaciones ilícitas',
    'cortejar',
    'delirio',
    'recreo',
    'temerario',
    'provocación',
    'aullido',
    'rapto',
    'chica fácil',
    'provocadora',
    'pícaro',
    'cazador',
    'pecaminosa',
    'voluptuoso',
    'fuga',
    'tentadora',
    'fusión',
    'seducción',
    'pájaro',
    'romance',
    'interacción',
    // Agrega más palabras según sea necesario
  ];
  
  const ForbiddenWords = () => {
    return forbiddenWords;
  };
  
  export default ForbiddenWords;
  